/* testdata.h */

static const struct
{
  const char *key;
  const char *value;
}
testdata[] =
{
  { "Accio", "summoning charm" },
  { "Aguamenti", "water emerges from tip of wand" },
  { "Alohomora", "unlocks doors" },
  { "Aparecium", "makes invisible ink become invisible again" },
  { "Avada Kedavra", "the killing curse (unforgivable)" },
  { "Avis", "birds fly out of wand" },
  { "Bubble-Head Charm", "used to breathe underwater" },
  { "Cave Inimicum", "a charm used to protect an area" },
  { "Colloportus", "makes doors seal themselves" },
  { "Confringo", "causes the target to explode" },
  { "Confundo", "causes confusion on the targeted person " },
  { "Crucio", "torturing curse (unforgivable)" },
  { "Deletrius", "a spell used to make things disappear or vanish" },
  { "Densaugeo", "causes front teeth to grow abnormally large" },
  { "Diffindo", "used to cut objects" },
  { "Dissendium", "a spell used to open or reveal secret passages" },
  { "Enervate", "revives someone who has been stunned or in a unconscious state" },
  { "Episkey", "a spell which can be used to heal people " },
  { "Evanesco", "makes things disappear" },
  { "Expecto Patronum", "used to repel dementors" },
  { "Expelliarmus", "disarming spell" },
  { "Fereverto", "transfigures creatures into a chalice" },
  { "Ferula", "used to create a sling" },
  { "Fidelius Charm", "used to conceal a secret within the responsible secret keeper" },
  { "Finite Incantatem", "finishes a spell" },
  { "Flagrate", "marks whatever pointed at with a fiery red X" },
  { "Flagranate Charm", "a charm that makes items burn you when they are touched" },
  { "Furunculus curse", "causes boils to appear on target’s face" },
  { "Gemino Charm", "a spell that makes things multiply when touched, but the copies are useless" },
  { "Homorphus Charm", "turns a werewolf back into a person" },
  { "Impedimenta", "slows down an attacking opponent " },
  { "Impervious", "used to repel water on glasses" },
  { "Incendio", "produces a fire" },
  { "Imobulus", "makes moving objects immobile" },
  { "Imperio", "complete control spell (unforgivable)" },
  { "Levicorpus", "(nonverbal) hangs the target upside down in the air by the ankles" },
  { "Liberacorpus", "(nonverbal) the spell that undoes the result of the Levicorpus spell" },
  { "Locomotor Charm", "a charm when put on an object makes it move" },
  { "Locomotor Mortis", "leg-locking curse" },
  { "Lumos", "produces a light from the tip of a wand" },
  { "Mobiliarbus", "moves objects" },
  { "Mobilicorpus", "moves ghosts that can’t move by themselves" },
  { "Morsmordre", "produces a dark mark" },
  { "Muffliato", "makes other people not be able to hear a conversation because of unidentifiable buzzing " },
  { "Nox", "extinguishes the light of the Lumos spell" },
  { "Obliviate", "a very powerful memory charm which causes a person to forget everything" },
  { "Orchidious", "produces flowers" },
  { "Petrificus Totalus", "full body bind spell" },
  { "Point Me", "the incantation used to make the wand act as a compass and point north" },
  { "Portus", "makes the item pointed at a portkey" },
  { "Priori Incantato", "makes the wand identify the last spell produced by it through a ghost-like image, also see Priori Incantatem in Terms section" },
  { "Protego", "protects from harmful spells" },
  { "Quietus", "a spell used to lower your voice" },
  { "Reducio", "decreases the size of something" },
  { "Reducto", "blasts objects out of the way" },
  { "Relashio", "causes a person or thing to release anything they are holding or bounding, or, if used underwater, sends a jet of boiling water" },
  { "Reparo", "repairs things" },
  { "Repello Muggletum", "repels against muggles around the designated area" },
  { "Rictasempra", "tickling charm" },
  { "Ridikulus", "turns a boggart into whatever a person is thinking of" },
  { "Salvio Hexia", "a protection charm" },
  { "Scourgify", "cleans things out" },
  { "Sectasempra", "makes deep cuts in the skin" },
  { "Serpensortia", "makes a snake emerge from the tip of the wand " },
  { "Silencio", "makes all noise cease" },
  { "Sonorous", "amplifies your voice" },
  { "Stupefy", "powerful stunning spell" },
  { "Tarantallegra", "makes a persons legs uncontrollably dance" },
  { "Tergeo", "a spell that cleans something off" },
  { "Undetectable Extension Charm", "makes things have extended space within, without increasing the size of the object" },
  { "Waddiwasi", "shoots out a wad of gum out" },
  { "Wingardium Leviosa", "floats objects into the air" },
};
